FROM michigantrafficlab/msight-core:latest-pytorch2.7.1-cuda12.8-cudnn9

# Install build tools and rsync
RUN apt-get update && \
    pip install --upgrade build

# Copy the original source to a temporary location
COPY . /app/msight-vision

# Set working directory
WORKDIR /app/msight-vision

# Install the obfuscated package
RUN pip install -e .
